# Generated by Django 5.0.2 on 2024-03-22 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=10)),
                ('class_name', models.CharField(max_length=100)),
                ('professor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_week', models.DateField()),
                ('end_week', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('id_number', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('enrolled_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.student')),
            ],
            options={
                'unique_together': {('student', 'enrolled_class')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(default=1)),
                ('attendance_type', models.CharField(help_text='Type of attendance', max_length=100)),
                ('attended', models.BooleanField(default=False)),
                ('recorded_by', models.ForeignKey(help_text='User who recorded the attendance', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.student')),
            ],
            options={
                'unique_together': {('student', 'class_ref', 'week')},
            },
        ),
    ]
